### PR TITLE
Rewrite of bwproxy

### PR DESCRIPTION
**Pull request by Uklusi**
The pull request is a reorganisation and rewrite of the program.

Main points are:
* Using Scryfall api instead of magicthegathering.io api;
* Reorganised the program, with a file containing constants and the drawUtils file in a subfolder;
* Added type hints; this brings the required python version to 3.7, since before then the typing library is slow;
* Added support for various card layouts, including split, aftermath, flip, adventure, and double-faced cards. Silver-bordered support is still not included;
* Changed the mana symbols (mainly hybrid and phyrexian mana, but also bigger monocolored mana), and added symbols in the rules text;
* Incorporated the basic lands generator in the main program, and removed the singleton limit;
* Added double-faced card indicators (only sun/moon for transforming), and changed the White color when printing colored cards (colored mana symbols still in progress);
* Bugfixes: Added P/T to vehicles, added a text replacing the color indicator, added colorless mana symbol;
* Added some customisation options and upped version number to 2.0.

Here there are some examples of the current output of the program, with various flags specified:

colored_1
Colored card frames, showing off the new hybrid and phyrexian mana symbols. The hybrid-phyrexian one, used in `Tamiyo, Compleated Sage`, is ugly, but I don't have any better ideas that are still legible.
Also in this page there are the color indicator text, the colorless and tap symbols in text, the removed singleton limit (double Ghostfire) and the page can be printed as A4 full size.

colored_2
Weird frames, in color. We have a fuse card, a split card, an aftermath card, an adventure card, a modal double-faced card, a flip card, and a transforming double-faced card

black_white
A repeat of the first page. This time the cards are in black and white, there are no symbols in the rules box, and there is only one pixel between cards

small
Black and white cards, at 75% scale and on a letter-sized page. This shows the flavor name for Godzilla, King of the Monsters (which was specified that way directly inside the decklist), the basic lands, and the addition of both Snow Basic Lands and Wastes.

### CODE REVIEW

**Comment by a11ce** [comment]
Hi, thank you so much, this looks absolutely amazing. I might not be able to review it for a week or so though. Out of curiosity, how did you find this project?

**Comment by Uklusi** [comment]
Hi, don't worry, I know it's a lot of code, there's no hurry.

I found about the project because I was looking for a black/white proxy generator on Google (ink is expensive!) and I came across your reddit post on r/EDH ( https://www.reddit.com/r/EDH/comments/osv3sc/bwproxy_beta_a_grayscale_mtg_proxy_generator/ ).

**Comment by delightfulagony** [comment]
Hi! First of all thank you both for this software!
I wanted to say that this PR uses the typing-extensions package but the README doesn't mention it

> Get dependencies with `python3 -m pip install scrython pillow tqdm`

Maybe want to add it there

> Get dependencies with `python3 -m pip install scrython pillow tqdm typing-extensions`

**Comment by a11ce** [comment]
Hi, to be honest, I forgot to come back to this. I'll give you repo access. Go to https://github.com/a11ce/bwproxy/invitations to join.

**Pull request merged**
